# Converting our generated data to vcf so it can be used with GNOMIX and LA

In [ ]:
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt
from my_knn_module.import_data import import_genome_data_as_df

## First we convert to *.hap*

In [2]:
ag_df = import_genome_data_as_df(filename='WGAN.hapt', labels=None)
ag_df.head()

Type Sample  0  1  2  3  4  5  6  7  ...  9990  9991  9992  9993  9994  \
0   AG    AG0  0  0  0  0  1  0  1  0  ...     0     0     0     0     0   
1   AG    AG1  0  0  0  0  0  1  1  0  ...     0     0     0     0     0   
2   AG    AG2  0  0  0  0  0  0  0  0  ...     0     0     0     0     0   
3   AG    AG3  0  0  0  0  0  0  0  0  ...     0     0     0     0     0   
4   AG    AG4  0  0  0  0  0  0  1  0  ...     0     0     0     0     0   

   9995  9996  9997  9998  9999  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 10002 columns]

In [3]:
ag_df = ag_df.drop(columns=['Type', 'Sample'])
ag_df.head()

0  1  2  3  4  5  6  7  8  9  ...  9990  9991  9992  9993  9994  9995  \
0  0  0  0  0  1  0  1  0  0  0  ...     0     0     0     0     0     0   
1  0  0  0  0  0  1  1  0  0  0  ...     0     0     0     0     0     0   
2  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
3  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
4  0  0  0  0  0  0  1  0  0  0  ...     0     0     0     0     0     0   

   9996  9997  9998  9999  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 10000 columns]

In [4]:
ag_df = ag_df.to_numpy().transpose()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
